In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [4]:
df = pd.read_csv("../data/raw/fake_and_real_news_dataset.csv")

In [5]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 4594
Columns : 4

In [6]:
df.columns

Index(['idd', 'title', 'text', 'label'], dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4594 entries, 0 to 4593
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   idd     4594 non-null   object
 1   title   4593 non-null   object
 2   text    4594 non-null   object
 3   label   4594 non-null   object
dtypes: object(4)
memory usage: 143.7+ KB

In [8]:
df.dtypes

idd      object
title    object
text     object
label    object
dtype: object

In [9]:
df.describe()

,idd,title,text,label
count,4594,4593,4594,4594
unique,4594,4537,4409,2
top,Fq+C96tcx+,Log In - New York Times,"Killing Obama administration rules, dismantlin...",REAL
freq,1,5,37,2297

In [10]:
df.isnull().sum()

idd      0
title    1
text     0
label    0
dtype: int64

In [11]:
df.dropna(inplace=True)

In [12]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [13]:
df["label"].unique()

array(['REAL', 'FAKE'], dtype=object)

In [14]:
df["label"].value_counts()

label
FAKE    2297
REAL    2296
Name: count, dtype: int64

In [15]:
df["label"].value_counts(normalize=True)*100

label
FAKE    50.010886
REAL    49.989114
Name: proportion, dtype: float64

In [16]:
df.sample(5)

,idd,title,text,label
2592,6WxRN&5%6C,Vladimir Putin – Straight From The Horse’s Mouth,"in: War Propaganda , World News If it’s not Is...",FAKE
2839,Kb6&Oe@W7G,WWN Guide To Preventing World War III,0 Add Comment \nIT HAS come to our attention t...,FAKE
2302,uhkf*Ev@_W,Russia prevented Spain from diplomatical confl...,Russia prevented Spain from diplomatical confl...,FAKE
3496,_Q+qx2i7v3,"Syrian War Report – November 4, 2016: Govt For...",Be the First to Comment! Leave a Reply Click h...,FAKE
2248,Vjfl_3gnDX,Trump Foundation lacks the certification requi...,Donald Trump’s charitable foundation — which h...,REAL

In [17]:
print("Title:\n")

print(df.loc[0,"title"])

print("\n")

print("News:\n")

print(df.loc[0,"text"])

print("\n")

print("Label : ",df.loc[0,"label"])

Title:

‘A target on Roe v. Wade ’: Oklahoma bill making it a felony to perform abortions waits for governor’s decision


News:

UPDATE: Gov. Fallin vetoed the bill on Friday. Head here for more.

Lawmakers in Oklahoma approved a bill Thursday that would make performing abortions a felony and revoke the medical licenses of most physicians who assist in such procedures.

This sweeping measure, which opponents described as unconstitutional and unprecedented, now heads to Gov. Mary Fallin (R). She will have five days — not including Sunday — to decide whether to sign the bill, veto it or allow it to become law without her signature, according to a spokesman.

“The governor will withhold comment on that bill, as she does on most bills, until she and her staff have had a chance to review it,” Michael McNutt, a spokesman for Fallin, said in an email.

The Oklahoma bill is the first such measure of its kind, according to the Center for Reproductive Rights, which says that other states seeking to ban abortion have simply banned the procedure rather than attaching penalties like this.

According to the measure, known as SB1552, a person who performs or induces an abortion will be guilty of a felony and punished with between one and three years in the state penitentiary.

This legislation also says that any physician who participates in an abortion — deemed “unprofessional conduct” in the bill — will be “prohibited from obtaining or renewing a license to practice medicine in this state.” However, medical licenses will not be stripped from doctors who perform abortions deemed necessary to save the mother’s life.

[Yes, hospitals perform abortions. This D.C. doctor says her hospital won’t let her talk about it]

The bill passed the Oklahoma House of Representatives with a vote of 59-to-9 last month. On Thursday, the state’s senate passed it with a vote of 33-to-12.

“Since I believe life begins at conception, it should be protected, and I believe it’s a core function of state government to defend that life from the beginning of conception,” State Sen. Nathan Dahm, a Republican who represents Tulsa County, told the Associated Press.

Dahm said he hopes the Oklahoma measure could eventually lead to the overturning of Roe v. Wade, the 1973 Supreme Court decision that recognized a woman’s right to an abortion. Dahm did not respond to messages seeking comment Thursday and Friday.

Dawn Laguens, executive vice president of Planned Parenthood Federation of America,  said last month that the Oklahoma bill is “a ban on abortion, plain and simple.” The legislation sent to Fallin on Thursday “is reckless and dangerous,” according to Ilyse Hogue, president of NARAL Pro-Choice America.

“This bill puts doctors in the cross hairs for providing women with the option of exercising our fundamental right to decide how and when to start a family,” Hogue said in a statement. “And it creates penalties for doctors doing their jobs: performing a safe and legal medical procedure.”

Liberty Counsel, a group that rose to national prominence last year defending the Kentucky clerk who refused to sign same-sex marriage licenses, said Friday that it had helped support the legislation in Oklahoma. The organization also vowed to defend it in court.

“This particular bill puts a target on Roe v. Wade,” Mat Staver, the group’s founder and chairman, said in an interview Friday. “It is Oklahoma’s line in the sand on the sanctity of human life, as standing on the side of protecting innocent children.”

Staver said that his group met with Oklahoma lawmakers before the legislation was filed, offering legal analysis after discussions had begun in the state about proposing such a measure.

The Oklahoma bill is “the first of its kind,” Staver said, though he said it was possible other states may follow Oklahoma’s lead.

“This is a bolt step in the right direction, in my view,” Staver said. “It will be challenged and we’re prepared to defend it.”

[Oklahoma isn’t the only state taking big steps to limit abortions]

The Oklahoma State Medical Association, which has called the measure “troubling,” has said it would not take a position on the legality of abortion as long as the practice remains legal. However, the group said it was opposed to “legislation that is designed to intimidate physicians or override their medical judgment.”

On Thursday, the group reiterated that opposition, calling it “one more insulting slap in the face of our state’s medical providers” and urging Fallin to veto the legislation.

“We are extremely disappointed in today’s vote,” Sherri Baker, president of the medical association, said in a statement Thursday. “It is simply unconscionable that, at a time when our state already faces a severe physician shortage, the senate would waste its time on a bill that is patently unconstitutional and whose only purposes are to score political points and intimidate physicians across this state.”

When the measure was debated in the state’s House of Representatives, a legislator who ultimately voted against the bill pointed to the group’s opposition and voiced concerns that the law could lead to doctors abandoning Oklahoma. But one of the bill’s co-sponsors said he did not think it would have an impact.

Since taking office in 2011, Fallin has signed more than a dozen bills restricting access to reproductive health care, the Center for Reproductive Rights, a nonprofit legal group, said Thursday.

The new bill “is blatantly unconstitutional and, if it takes effect, it will be the most extreme abortion law in this country” since the Roe v. Wade decision, Amanda Allen, senior state legislative counsel at the center, wrote in a letter to Fallin on Thursday.

Allen said her group was urging Fallin to veto the legislation, which she said was part of a larger pattern of lawmakers in the state chipping away at abortion rights.

“Policymakers in Oklahoma should focus on advancing policies that will truly promote women’s health and safety, not abortion restrictions that do just the opposite,” Allen wrote. “Anti-choice politicians in the state have methodically restricted access to abortion and neglected to advance policies that truly address the challenges women and families face every day.”

Allen also said that the bill would “almost certainly lead to expensive court challenges that the state of Oklahoma simply cannot defend in light of longstanding Supreme Court precedent.”

Fallin has until next week to make a decision on the bill. If this measure does become law, it would go into effect on Nov. 1.

The forgotten history of Justice Ginsburg’s criticism of Roe v. Wade

Indiana banned abortions if fetuses have Down syndrome

This story, first published on Thursday, has been updated on Friday to include Liberty Counsel’s comments.


Label :  REAL

In [18]:
df["text_length"] = df["text"].apply(len)

In [19]:
df["text_length"].head()

0    6677
1    4044
2    3274
3    5316
4    2660
Name: text_length, dtype: int64

In [20]:
print(df["text_length"].mean())

4862.717831482691

In [21]:
df[df["text_length"]==df["text_length"].max()]

,idd,title,text,label,text_length
3294,eydp4vvCP^,Re: Why Are So Many People Choosing To Leave T...,Why Are So Many People Choosing To Leave The U...,FAKE,115372

In [22]:
df.head()

,idd,title,text,label,text_length
0,Fq+C96tcx+,‘A target on Roe v. Wade ’: Oklahoma bill maki...,UPDATE: Gov. Fallin vetoed the bill on Friday....,REAL,6677
1,bHUqK!pgmv,Study: women had to drive 4 times farther afte...,Ever since Texas laws closed about half of the...,REAL,4044
2,4Y4Ubf%aTi,"Trump, Clinton clash in dueling DC speeches","Donald Trump and Hillary Clinton, now at the s...",REAL,3274
3,_CoY89SJ@K,Grand jury in Texas indicts activists behind P...,A Houston grand jury investigating criminal al...,REAL,5316
4,+rJHoRQVLe,"As Reproductive Rights Hang In The Balance, De...",WASHINGTON -- Forty-three years after the Supr...,REAL,2660

In [23]:
df.to_csv("../data/processed/basic_clean.csv",index=False)

In [24]:
print("="*50)
print("Dataset Loaded Successfully")
print("Rows :",df.shape[0])
print("Columns :",df.shape[1])
print("Missing Values :",df.isnull().sum().sum())
print("Duplicate Rows :",df.duplicated().sum())
print("="*50)

==================================================
Dataset Loaded Successfully
Rows : 4593
Columns : 5
Missing Values : 0
Duplicate Rows : 0
==================================================